### PR TITLE
Upgrade to Hyrax ~>2.3.0

### PR DESCRIPTION
**Pull request by cjcolvar**
This is just a refresh of #1543 to see if the failing tests are magically fixed.

### CODE REVIEW

**Comment by orangewolf** [comment]
damn no magic. I have high hopes of digging in to this next week after I run my workshops

**Comment by geekscruff** [comment]
@cjcolvar I fixed the importer errors in #1548 but there are still the 4 AWS S3 ones which I had thought were fixed a while back by @orangewolf

**Comment by cjcolvar** [comment]
Maybe #1539 didn't actually help but caused these aws failures?  How about reverting that PR for now?  It seems like it might unblock this PR and thus also #1545 since they are both local branch and not in forks.

**Comment by geekscruff** [comment]
Let me try that now ...

**Comment by geekscruff** [comment]
@cjcolvar no joy #1549 same 4 errrors. I'm stumped!

**Pull request merged**
