### PR TITLE
update FactoryGirl to FactoryBot

### LINKED ISSUE #1530: Update FactoryGirl to FactoryBot
### Descriptive summary

FactoryGirl has been renamed FactoryBot. We should switch out the name to remain compatible with future updates and to better match upstream dependencies like Hyrax.

### PR DESCRIPTION
**Pull request by nwoodward**
Resolves #1530

Replaces FactoryGirl with FactoryBot

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by orangewolf** [comment]
@nwoodward thank you for this! looks like we have some rubocop failures. Can you work through those?

**Comment by nwoodward** [comment]
Sure. I'll take a look.

**Comment by nwoodward** [comment]
I think the rubocop failures are fixed. I'm not sure about the source of the new errors.

**Comment by orangewolf** [comment]
this is part of a set of failing specs that have nothing to do with a change. Going to investigate, I'm betting a dns entry changed or something like that

**Pull request merged**
